### ISSUE TITLE
Cabinet Home Page FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#10]
_From @danakonovalenko on March 16, 2018 12:2_

After authorization in Cabinet I want to see 
- [x] steps what should I do in order to make declaration or my [current declaration](https://edenlab.atlassian.net/wiki/x/tAGxGQ) in case I already signed one
- [x] my user's info [spec](https://edenlab.atlassian.net/wiki/x/L4AoGg)
according to [design](https://marvelapp.com/7i06dia/screen/39668285)

_Copied from original issue: edenlabllc/ehealth.api#1957_

**Comment by svetavedmed** [comment]
- declaration id -> decoration number
- dictionaries 
- dates format
- print
- back to declaration list
- division contact data to table
- dates in table

**Comment by kiurchv** [comment]
@svetavedmed Ready for testing
