### ISSUE TITLE
empty fields on preview print form

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#109]
in case field in empty it should nor be printed on preview print form
Пацієнт
- По-батькові
Контактна особа у разі екстренного випадку
- ПІБ (Ло undefined Ло)
Законні представники пацієнта
- ПІБ (По-батькові)
- Документ, що посвідчує повноваження законного представника (issued_at, issued_by)
Лікар
Лікар

**Comment by ephor** [comment]
duplicate #110
