### ISSUE TITLE
Create Declaration Request via Cabinet FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#11]
_From @danakonovalenko on March 16, 2018 13:16_

As an authorized patient I want to be able to create declaration request online.
In order to be able to do such after choosing doctor and division I need to have
- [x] button "create declaration request"  [spec](https://uaehealthapi.docs.apiary.io/#reference/internal.-cabinet/cabinet/create-declaration-request-online) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/436732204/Create+declaration+request+online), [business process](https://edenlab.atlassian.net/wiki/spaces/EH/pages/426443813)
- [x] view declaration form with filled data

_Copied from original issue: edenlabllc/ehealth.api#1958_

**Comment by lymychp** [comment]
looks like kong config issue @AlexKovalevych

**Comment by kiurchv** [comment]
Fixed
