### ISSUE TITLE
Terminate Declaration via Cabinet FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#13]
_From @danakonovalenko on March 16, 2018 13:25_

As an authorized patient after I signed a declaration I want to be able to terminate it.
In order to be able to do such I need to have button 'Terminate declaration' ([spec](https://edenlab.atlassian.net/wiki/x/N4CxGQ)) with pop-up approve window. After termination return to page with 'Declaration History'.

_Copied from original issue: edenlabllc/ehealth.api#1960_

**Comment by lymychp** [comment]
@danakonovalenko @SmartBBC please add link to design

**Comment by svetavedmed** [comment]
- [ ] Can we put everything in center?
![Screen Shot 2018-06-26 at 15.09.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f56b7191a379ea0c2b58415e4dbe5d4a1f06a3a3dc78e2a436628f550abc856c0a7cc53b14f8ee851fbe02e9748a1ed3b5ed9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb58f64ae44c54a4123463f43b.png)
