### ISSUE TITLE
Patient cabinet crowd testing results PL-2

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.web#159]
env: Chrome Version 67.0.3396.99
1. Select Doctor using map doesn't work
**repro steps:**
  * got to step.1, select [map](https://account.dev.asclepius.com.ua/search/map?lat=49.25740962436784&lng=23.843693484531514&zoom=22)
  * select any division and click `Детальніше`
![image](https://user-images.githubusercontent.com/5257001/43060293-ee50e960-8e58-11e8-9671-619d3af1f68c.png)
**Actual result:** nothing changed
**Expected result:** redirect to the selected division's list of doctors 
2. Search doctor using list doesn't work - parent of #177
**repro step:**
  * got to step.1, [select list](https://account.dev.asclepius.com.ua/search?lat=50.4021368&lng=30.452510699999948&zoom=9)
  * type in `Київ` into `населений пункт`
**Actual result:**: 
  * there is no `Київ` in the resulted list
  * 6 backend calls has happened
**Expected result:** 
  *  there should be `Київ` in the resulted list
  * only 1 backend call should happen
![image](https://user-images.githubusercontent.com/5257001/43060452-aeb56b2c-8e59-11e8-83ac-0b58506cbdbf.png)
3.  Редагування профілю не працює - parent of edenlabllc/ehealth.api#2882
**repro steps:**
  * go to `https://account.dev.asclepius.com.ua/profile/edit`
  * edit profile, change settlement and region to `Коломия`, `Івано-франківська`
  * sign using DS
**actual result:**
  * no information results of the edit operation. It is not clear whether success or not
  * address hasn't been changed
  * redirected to the edit profile page
**expected result:**
  * message or visual communication to user about the edit operation result
  * address should be changed
  * should be redirected to the profile page with the updated info (not edit mode)
4. security page loop
**repro steps:**
  * login using profile without 2FA
  * go to security [page](https://account.dev.asclepius.com.ua/security)
  * click `авторизації`
![image](https://user-images.githubusercontent.com/5257001/43061747-0f8a2ffa-8e5f-11e8-81c8-56542ee98f0a.png)
  * login using DS
**Actual result:**
  * after login user is redirected to `https://account.dev.asclepius.com.ua/`
**Expected result:**
  * user is redirected to the security page with the possibility to change 2FA.
------------------
**Proposed Enhancements:**
  * All the filtration fields should be hidden on the page `https://account.dev.asclepius.com.ua/search/map`
![image](https://user-images.githubusercontent.com/5257001/43060390-6ebb4410-8e59-11e8-9b2d-e6dd3609c6c6.png)
  * list of doctors should be filtered by `speciality` depends on the age of the cabinet user.
  * change text on the page `https://account.dev.asclepius.com.ua/security`: `На жаль, другий фактор авторизації був скинутий.` change to `Другий фактор авторизації не встановлено.`

**Comment by SmartBBC** [comment]
Design issues:
- Wrong font. Need to be: Gotham Pro. Now: System ui 
- Error page (wrong font and message):
![image](https://user-images.githubusercontent.com/12151072/43139022-566b2398-8f59-11e8-98ed-a6a62b95262d.png)
- Tables have no pagination
- Table search fields (the first option always should be shown in the dropdown list)
![image](https://user-images.githubusercontent.com/12151072/43139487-8506d930-8f5a-11e8-960a-cf27b47730a8.png)
- Map search: wrong Inactive input : text transparency should be 20%, only Name and Speciality fields should be inactive
- Flow steps are missing
![image](https://user-images.githubusercontent.com/12151072/43152474-4e057e56-8f77-11e8-9f8c-7f02ec9e0bcb.png)
- Wrong Doc Details page (Missing: flow steps, Back to list (bottom) button , Send declaration request (top) button)
![image](https://user-images.githubusercontent.com/12151072/43153278-8111aa5c-8f79-11e8-94d5-5e25f43dbfb7.png)
