### ISSUE TITLE
Show error in Cabinet

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#168]
![image](https://user-images.githubusercontent.com/30794602/43187409-fb63157c-8ff9-11e8-9737-047e9c1a6784.png)

**Comment by andriy-ilin** [comment]
@AlexKovalevych 
Need changes in response
1. entry -> "$.data"
2. rule -> "invalid_confidant_person"

**Comment by svetavedmed** [comment]
"Довірена особа обов'язкова для осіб віком до 14 років"
