### ISSUE TITLE
Cabinet fixes on Sign Up

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#178]
1. do not use filter on dropdown for DS 
![image](https://user-images.githubusercontent.com/30794602/43628992-8b06131c-9704-11e8-8e2a-c4f13b7b5a9f.png)

2. Use 70% black color for non editable fields
![image](https://user-images.githubusercontent.com/30794602/43629019-a78d6616-9704-11e8-895f-75a721830ba9.png)

3. Make calendar for all data fields
![image](https://user-images.githubusercontent.com/30794602/43629034-b6ae74b4-9704-11e8-885e-1a2eff27866a.png)

4. The end of dropdown should not be on the center of the field
![image](https://user-images.githubusercontent.com/30794602/43629069-d03871be-9704-11e8-8487-34eb76e14189.png)

5. move field description to the corner of the field, if data is entered
![image](https://user-images.githubusercontent.com/30794602/43629361-b307ae74-9705-11e8-8ada-dca48b273246.png)

6. change "Контактна особа у разі екстренного зв'язку" to "Контактна особя для екстреного зв'язку" 

7. On Changing area city should be reseted
*repo steps*
* goto edit profile
* change area
*actual result* - city is still from another area
*expected result* - as city is connected to area it should be reseted when area is changed

**Comment by svetavedmed** [comment]
5.
_документ_
- Серія
- Номер
- Ким виданий
- дата видачі

_Адреса реєстрації та Адреса проживання_
- Область
- Назва населеного пункту
- Ідекс
- Тип вулиці
- Назва вулиці
- № буд.
- № квартири

_Пароль_
- пароль

_Контактна особа для екстреного зв'язку_
- ім'я
- прізвище
- по-батькові

_слово-пароль_
- слово-пароль

**Comment by andriy-ilin** [comment]
select don't use Label inside Input:
- Область
- Назва населеного пункту
- Тип вулиці

**Comment by svetavedmed** [comment]
<img width="448" alt="google chrome_2018-08-30 10-41-34 2x" src="https://user-images.githubusercontent.com/30794602/44837112-5a249a00-ac41-11e8-9d08-a0d79b14edc1.png">
