### ISSUE TITLE
Contract Requests list page

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#186]
As NHS I want to see Contract Requests list in next view and with next possibilities:

- filter by (and/or)
     - edrpou (input field)
     - contract_number (input field)
     - status (drop-down list)
     - start/end date for contract_request.start_date
     - start/end date for contract_request.end_date

- sort by (or) / (asc/desc) (each next sort starts from default)
     - edrpou
     - status
     - contract_request.start_date
     - contract_request.end_date

- grid with fields
    - id
    - edrpou
    - contract_number
    - contract_request.start_date (контракт діє з)
    - contract_request.end_date   (контракт діє по)
    - status
    - details
    - contractor_legal_entity_id
    - ?contractor_legal_entity_name
    - ?contractor_owner_id
    - ?contractor_owner_name

- additional possibilities 
   - change columns' width
   - show contract_request_id with focus on that field and pop-up window with possibility to copy this id
  - expand long text (on focus) if column height is not enough to fit that text
   - add/delete columns to grid
       - columns order is without change. it's not allowed to change order of columns
       - at least one column must be chosen. do not allow to choose 0 column
       - save customers settings and reset them only by clicking on the button "reset settings"

**Comment by SmartBBC** [comment]
https://www.dropbox.com/s/yzvvavwrl0if9sj/Contract_requests_no_drpdwn.png?dl=0
https://www.dropbox.com/s/5rzdo9aobf7rkpj/Contract_requests.png?dl=0
https://www.dropbox.com/s/tfiybvd6pquqqur/Contract_requests_tooltip.png?dl=0

**Comment by danakonovalenko** [comment]
I have a proposition to make multi choice for drop-down fields (as status), to be able to choose contract request in few status [NEW, PENDING_NHS_SIGN] (as an example)

**Comment by SmartBBC** [comment]
Support status multichoise
https://www.dropbox.com/s/10kzznhsgzdzkdc/Contract_requests_status_dpdwn.png?dl=0

**Comment by SmartBBC** [comment]
Restore settings option was added
https://www.dropbox.com/s/y46hj2c193cgxaz/Contract_requests_restore_settings.png?dl=0

**Comment by danakonovalenko** [comment]
duplicated by  #368
