### ISSUE TITLE
Contract Request Details page

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#190]
As NHS admin I must have a possibility to receive info related to contract request.

Page has next logical blocks:

- contract_request_id
- status
- buttons:
     - `DECLINE/APPROVE` for contract_request in status `NEW`
     - `Get Printout form` for contract_request in status `PENDING_NHS_SIGN`, `NHS_SIGNED`, `SIGNED`
     - `Sign Contract Request` for contract_request in status `PENDING_NHS_SIGN`
- tabs
    - general info
    - legal_entity
    - divisions
    - employees
    - external_contractors
    - documents

----
1) **GENERAL INFO**

*block 1*
- start/end dates
 - contractor_rmsp_amount

*block 2*: nhs_signer
 - in case status contract_request  <> ('NEW', 'TERMINATED')
    - nhs_signer_id
    - nhs_signer_name
    - nhs_signer_base
    - nhs_contract_price
    - nhs_payment_method
    - issue_city
----

2) **LEGAL ENTITY**

*block 1*: contractor_legal_entity
- contractor_legal_entity.id
- contractor_legal_entity.name
- contractor_legal_entity.edrpou
- contractor_legal_entity.addresses

*block 2*: contractor_payment_details
- bank_name
- MFO
- payer_account

*block 3*: contractor_owner
 - id
 - first_name & last_name & second_name
 - base

----
3) **DIVISIONS**
on the tab must be **table** with **scroll** possibility. also paging size possibilities must be present
?!! it's not allowed to change columns width and order 

*grid*

- id
- name
- addresses
- mountain_region
- phone_number
- email
- go to employees (switch to `employees` tab filtered by division_id) 

----

4) **EMPLOYEES**

possibility to choose page sizing 

?!! it's not allowed to change columns width and order 

*filter*
- division_name (input field, like)

*grid*
- id
- first_name & last_name & second_name
- speciality
- staff_unit
- declaration_limit

----
5) ***EXTERNAL CONTRACTORS***
???
----

6) ***DOCUMENTS***

tab with icons and links to receive documents in pdf format

**Comment by SmartBBC** [comment]
https://www.dropbox.com/s/msm1f27u1dvjhrk/Contract_requests_general_info.png?dl=0
https://www.dropbox.com/s/z1xhb3sqzghzg8u/Contract_requests_details_med.png?dl=0
https://www.dropbox.com/s/r6zxcm2d3e5c0c7/Contract_requests_details_division.png?dl=0
https://www.dropbox.com/s/20svgzik3kcc1k8/Contract_requests_details_employee.png?dl=0
https://www.dropbox.com/s/oe4dfa6vfqt1x96/Contract_requests_subs.png?dl=0
https://www.dropbox.com/s/b0ewz15qp0w5lic/Contract_requests_docs.png?dl=0

**Comment by SmartBBC** [comment]
GENERAL INFO
- updated

LEGAL ENTITY
- updated

divisions tab:
- due to the fact that there is could be more than 20 divisions, I think search is needed
- scroll will appear if more columns will be added (user can add id for display from dropdown list)

employees tab: 
- updated

documents:
- icons were added

- https://www.dropbox.com/s/m9xd2vhf4zkzjo2/Contract_requests_pending_status.png?dl=0
- updated
- here is an option for external contractors table and subtable
https://www.dropbox.com/s/oe4dfa6vfqt1x96/Contract_requests_subs.png?dl=0
https://www.dropbox.com/s/l45v8x2cp9nojnz/Contract_requests_subs_subtable.png?dl=0

**Comment by danakonovalenko** [comment]
duplicated with Get Contract Request Details QraphQL #369
