### ISSUE TITLE
Decline Contract Request

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#194]
As NHS admin I need to have a possibility to Decline Contract Request in status = 'NEW'

This is a multi step process and must starts in new window. Each page must be with possibility to go to next step (if current step was filled) and return to the previous step.

***first step:***

- status_reason (input field)

additional_fields (without edit possibility)
- contract_request_id
- contractor legal entity
   - id
   - name
   - edrpou
- next_status
- consent_text

this page also must contain note with agreement.

***second step:***

digital signature

- choose center of DS certification 
- DS
- password

return to Contract Request details page with updated `status`

**Comment by SmartBBC** [comment]
Tooltip with consent text appeared when cursor on the button

https://www.dropbox.com/s/7q3ee95lutyd09r/Contract_requests_decline.png?dl=0
https://www.dropbox.com/s/bq4lahozmig1cvd/Contract_requests_decline_tooltip.png?dl=0
https://www.dropbox.com/s/urzi9kuc9qio0oz/Contract_requests_decline_s2.png?dl=0
https://www.dropbox.com/s/m9xd2vhf4zkzjo2/Contract_requests_pending_status.png?dl=0

**Comment by danakonovalenko** [comment]
duplicated with Decline Contract Request GraphQL #373
