### ISSUE TITLE
OAuth flow missing links

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#2]
_From @danakonovalenko on March 21, 2018 9:56_

- [x] After reset password, in case the token expired there is no any option for user:

<img width="713" alt="screen shot 2018-03-21 at 11 51 14 am" src="https://user-images.githubusercontent.com/31403196/37703388-3401287e-2cfe-11e8-8fcf-735e5d4ed4e5.png">

change according to new design: https://marvelapp.com/7i06dia/screen/39994099

- [x] in case after employee update with existing user an invitation was sent to email there is no option to reset password
<img width="676" alt="screen shot 2018-03-21 at 11 55 16 am" src="https://user-images.githubusercontent.com/31403196/37703561-c37bea0c-2cfe-11e8-9172-211075a37ff0.png">
add option "Забули пароль?"

_Copied from original issue: edenlabllc/ehealth.api#1981_

**Comment by lymychp** [comment]
@svetavedmed please test and close

**Comment by lymychp** [comment]
![image](https://user-images.githubusercontent.com/5257001/42149081-6a1d56e6-7ddd-11e8-8d39-4fd2c9da02d3.png)
