### ISSUE TITLE
Declaration List page

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#210]
As NHS admin I want to have access to Declarations List knowing it ID or NUMBER. So we need to have a page

***DECLARATIONS SEARCH***

This page should be filled only after filter were inputed

- search by 
   -  id / declaration_number (input field)

---
- grid with fields (same for both pages)
  - declaration_number
  - legal_entity_name
  - legal_entity_edrpou
  - declarations.start_date
  - patient_name
  - details
  - division_name
  - division_address (region+district+settlement)
  - declaration_id (hidden)
 

- additional possibilities for page
  - change columns' width
  - show declaration id with focus on that field and pop-up window with possibility to copy this id
  - expand long text (on focus) if column height is not enough to fit that text
  - add/delete columns to grid
  - columns order is without change. it's not allowed to change order of columns
  - at least one column must be chosen. do not allow to choose 0 column
  - save customers settings and reset them only by clicking on the button "reset settings"

**Comment by SmartBBC** [comment]
https://www.dropbox.com/s/cxf449r9jr5ogmi/Declarations_list.png?dl=0
https://www.dropbox.com/s/punjckhu174727d/Declarations_list_drpdwn.png?dl=0

**Comment by SmartBBC** [comment]
Here are updated pages
https://www.dropbox.com/s/qlfu7kzwxr4pxn7/Declarations_list_number.png?dl=0
https://www.dropbox.com/s/wzwcj6jdnabuc1e/Declarations_list_number_table.png?dl=0
https://www.dropbox.com/s/ayu85plkdbytqk9/Declarations_list_number_table_drpdwn.png?dl=0
https://www.dropbox.com/s/kyd7hcc6cd2omhx/Declarations_list_patient.png?dl=0

https://www.dropbox.com/s/ai6gwo0jsxoskka/Declarations_pendig_verification_list.png?dl=0
