### ISSUE TITLE
Search for a person NHS admin portal v2

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#263]
As NHS admin I want to be able to ***search for a person*** using next possible filter parameters:

---
***possibility 1:***
- tax_id

***possibility 2:***
- phone_number

***possibility 3:***
- first_name
- last_name
- birth_date

***possibility 4:***
- unzr

---
After search NHS admin should be able to see the list of person(s) with next fields (***grid***):
```
- person_name (first & second & last)
- birth_date
- tax_id
- unzr
- authentification_method
- details
```
with possibility to ***sort by*** birth_date, tax_id, unzr.

---
Clicking on ***details page*** NHS admin must be able to see 

***in header***
```
- person_id 
- person_status
```

and ***tabs***

1) ***personal info***
```
- first_name & second_name & last_name
- birth_date
- birth_country
- birth_settlement
- tax_id
- unzr 
- phones
```
2) ***authentication_method***
```
- type
-  number (in case type='OTP')
- documents 
- ***button*** Reset authentication method.
by clicking on button to show notification message with approve.
after that return to authentication_method tab
```
3) ***declarations***
grid with fields 

```
- declaration_number
- legal_entity_name
- legal_entity_edrpou
- start_date
- status
- division_name
- division_address (region+district+settlement)
- details
- patient_name (hidden)
- declaration_id (hidden)
```
also NHS admin must be able to sort by status, start_date

parent of #282
parent of #283
parent of #285

**Comment by SmartBBC** [comment]
https://www.dropbox.com/s/qlfu7kzwxr4pxn7/Declarations_list_number.png?dl=0
https://www.dropbox.com/s/kyd7hcc6cd2omhx/Declarations_list_patient.png?dl=0

https://www.dropbox.com/s/as4qc8yrjjolij7/Patient_details_authentification_method.png?dl=0
https://www.dropbox.com/s/81f1eia4mcfgfq2/Patient_details_declarations.png?dl=0
https://www.dropbox.com/s/q9f4r33zb947tmn/Patient_details_general_info.png?dl=0

**Comment by SmartBBC** [comment]
Please see a few design issues here:
https://www.dropbox.com/s/ydhlp34jyee6vkx/Patient_list_search_design_issues.png?dl=0
