### ISSUE TITLE
Reset Authentication Method 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#282]
As NHS admin I want to find a patient and reset his authentication method

[Reset Authentication Method WS](https://uaehealthapi.docs.apiary.io/reference/internal.-nhs-admin-v2/persons/reset-authentication-method)

[design](https://www.dropbox.com/sh/xnclss2bfkbdj9t/AAB_wVX2txm0nsUQDuc5gkaja?dl=0&preview=Patient_details_authentification_method.png)

Child of #263

**Comment by ephor** [comment]
blocked by #335

**Comment by danakonovalenko** [comment]
in case person is inactive button reset authentication method should be disabled
