### ISSUE TITLE
Legal entity list page

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#319]
NHS admin must be able to get legal entities details described in [scheme](
https://github.com/edenlabllc/ehealth.web/blob/master/packages/mock-server/__schema__/legal_entities.graphql) and [features](
https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/legal_entities_details.feature)
```
- legalEntities( filter: LegalEntityFilter orderBy: LegalEntityOrderBy ): [LegalEntity]
```

**Comment by svetavedmed** [comment]
- [ ] can't order table by nhsVerified_ASC, nhsVerified_DESC
