### ISSUE TITLE
Create related legal entities

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#322]
As NHS admin I want to be able to set related legal entities (legator/successor).
For this we need to have a page based on [logic](https://edenlab.atlassian.net/wiki/x/zQDiJQ), [spec](
https://github.com/edenlabllc/ehealth.web/blob/master/packages/mock-server/__schema__/legal_entities.graphql) and [use_cases](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/legal_entities_details.feature)

**Comment by lymychp** [comment]
jobs should be added

**Comment by svetavedmed** [comment]
- [ ] on the page `https://admin.dev.asclepius.com.ua/legal-entities/8aedd3fe-be5c-40ae-8034-3fd1678ce9d5/add/sign` if try to go on the same page by  the link
![Google Chrome_2018-10-08 17-35-25@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46cf9b95248e86e9ace1ad4ca958cfc679177f3e7854ee7b28c5b27ff2112e4c5d5a3eae094a4356bcbbd671f3e57862804e0ee4d03c0b75933512aabdd649b801bb23d81b84e7ea891dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e14d5ca0123563e47f2431.png)

I get an error

![Google Chrome_2018-10-08 17-35-37@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599532ee55bb58001fdeacee/125516c66e82c728ace21e0d46cf9b95248e86e9ace1ad4ca958cfc679177f3e7854ee7b28c5b27ff2112e4c5c583eae094a4356bcbbd671f3e57862804e0ee4d03c0b75933512aabdd649b801bb23d81b84e7ea891dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e14d5ca71a3061e77e2431.png)

react-dom.production.min.js:169 TypeError: Cannot read property 'edrpou' of undefined
    at DefinitionList.js:18
    at Array.filter (<anonymous>)
    at t.a (DefinitionList.js:18)
    at Zo (react-dom.production.min.js:150)
    at react-dom.production.min.js:162
    at Ai (react-dom.production.min.js:193)
    at Fi (react-dom.production.min.js:194)
    at ha (react-dom.production.min.js:206)
    at da (react-dom.production.min.js:205)
    at Mi (react-dom.production.min.js:201)

**Comment by svetavedmed** [comment]
- [ ] chrome-extension://bpconcjcammlapcogcnnelfmaeghhagj/edit.html?video
