### ISSUE TITLE
person search in NHS Admin

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#328]
repo steps:
goto https://admin-legacy.dev.asclepius.com.ua/persons
enter first_name, last_name, birth_date
search
and search again with the same parameters

Actual result: error for empty fields
Expected result: no error

done on dev

Acceptance Criteria: delivered to demo, preprod, prod

**Comment by lymychp** [comment]
should be delivered to prod

**Comment by ephor** [comment]
blocked by #338

**Comment by ephor** [comment]
delivered to preprod
