### ISSUE TITLE
Assign Contract Request GraphQL

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#370]
As NHS admin I want to be able to assign Contract Requests to NHS employees using new admin portal.
In order to do that WS must be implemented based on 
- [x] [confluence](https://edenlab.atlassian.net/wiki/x/X4FLJw) / [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/contractRequests.graphql)
- [x] for Update/Approve/Decline check contract_request.status=IN_PROCESS (as for now status=NEW)
- [x] implement
- [x] test

**Comment by lymychp** [comment]
blocked by #3194
