### ISSUE TITLE
Approve Contract Request GraphQL

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#372]
As NHS admin I want to be able to Approve Contract Request using new admin portal.
So, we need to implement mutation using graphql
- [ ] [confluence](https://edenlab.atlassian.net/wiki/x/JABBHw) / [schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/contractRequests.graphql) / features
- [ ] implement 
- [ ] test

**Comment by lymychp** [comment]
duplicates #371
