### ISSUE TITLE
Terminate Contract GraphQL

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#377]
As NHS admin I want to be able to get Terminate Contract using new admin portal.
So, we need to implement mutation using graphql
- [x] [confluence](https://edenlab.atlassian.net/wiki/x/d4C2Hw) / [schema]() / features / [design](https://marvelapp.com/5e16635/screen/48869282)
- [x] implement 
- [ ] test

blocked by #376
blocked by #375

**Comment by lymychp** [comment]
blocked by #376
blocked by #375
