### ISSUE TITLE
Filter LE by settlement

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#427]
Instead of mock data we should user real data from UA Addresses services
- [ ] implement
- [ ] test

**Comment by ephor** [comment]
Blocked by https://github.com/edenlabllc/ehealth.api/issues/3355

**Comment by ephor** [comment]
Blocked by edenlabllc/ehealth.api#4281

**Comment by svetavedmed** [comment]
is blocked by edenlabllc/ehealth.api#3355
