### ISSUE TITLE
Reimbursement contract list

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.web#492]

**Comment by svetavedmed** [comment]
- [ ] error 500 on search by edrpou
![image.png](https://zube.io/files/edenlabllc/f35ce242dd5d91baf16db4a49298b6fa-image.png)

**Comment by svetavedmed** [comment]
- [ ] after returning back to the list from contract details page, I do not see grid of contracts. I can fix it with reloading the page
![Screen Shot 2018-12-22 at 5.44.08 PM.png](https://zube.io/files/edenlabllc/878e59be77ab850b47b40a7f43cf9d4b-screen-shot-2018-12-22-at-5-44-08-pm.png)

**Comment by svetavedmed** [comment]
- [ ] change all date to Ukrainian format
