### ISSUE TITLE
Terminate Declaration on Admin portal (FE)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#636]
Declaration in status `active` can be terminated. In order to do that we should add implemented mutation on NHS Admin portal
```
 terminateDeclaration(
    input: TerminateDeclarationInput!
  ): TerminateDeclarationPayload
```
[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/index.graphql)
[features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature)

**Comment by danakonovalenko** [comment]
is blocked by edenlabllc/ehealth.api#3925

**Comment by ephor** [comment]
> in case person is inactive button reset authentication method should be disabled

I think it is the wrong task. But I fixed it. Should I move this task in the test, or wait until a blocked task will be fixed?

**Comment by danakonovalenko** [comment]
yes, it's related to task #282, which have been closed. We should wait until back is ready
