### ISSUE TITLE
page for delclarations in status pending_verifications FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#645]
As NHS admin I want to be able to see declarations in status `PENDING_VERIFICATION'. In order to do that we need to have page with applied list  
```
pendingDeclarations(
    "A condition to be used in determining which values should be returned by the collection."
    filter: DeclarationFilter
    "The method to use when ordering collection items."
    orderBy: DeclarationOrderBy
    "Read all values in the set after (below) this cursor."
    after: String
    "Read all values in the set before (above) this cursor."
    before: String
    "Only read the first _n_ values of the set."
    first: Int
    "Only read the last _n_ values of the set."
    last: Int
  ): DeclarationConnection!
```
[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/index.graphql) / [features](https://github.com/edenlabllc/ehealth.web/blob/master/packages/admin/e2e/__features__/declaration_details.feature)

**Comment by danakonovalenko** [comment]
- [ ] there are 3 patients with no_tax_id in DB, however I can see only 2 with such flag on list
- [ ] order by no_tax_id is not correct

**Comment by burlachenkovv** [comment]
Person's and Declaration's noTaxId values are out of synch: https://tppr.me/P6RLC
We need to clean up the base.

**Comment by danakonovalenko** [comment]
there is no area for addresses, please fix address
![image.png](https://zube.io/files/edenlabllc/b573a075f045a784bb300dbf62309779-image.png)
