### ISSUE TITLE
Add possibility to upload patient entity type registers

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.web#658]
As NHS admin
I want to be able to [upload](https://admin-legacy.dev.asclepius.com.ua/registers/upload) `patient` type registers along with the declaration type.
So that I can [upload death registration registers](https://edenlab.atlassian.net/wiki/spaces/EH/pages/344031370/AUTO+Terminate+declaration)

**Comment by danakonovalenko** [comment]
tested, on demo and preprod
