### ISSUE TITLE
Assign new merge candidate in order to be reviewed (FE)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#669]
As NHS admin reviewer of manual merge requests I want to be able to assign merge candidate to review. 

In order to do that we need to apply implemented mutation based on [logic](https://edenlab.atlassian.net/wiki/x/sIBUKg) , spec and features

- [x] implement

- [x] test

**Comment by ephor** [comment]
Blocked by https://github.com/edenlabllc/ehealth.api/issues/4032
