### ISSUE TITLE
Get details of merge request FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#673]
As NHS admin I want to see details of merge request I reviewing in order to make decision on it

We need to have a page with details based on

- [x] schema / features
- [x] implement 
- [x] test

**Comment by ephor** [comment]
Blocked by https://github.com/edenlabllc/ehealth.api/issues/4036

**Comment by svetavedmed** [comment]
- [ ] change "Основна довірена особа.Дата народження" to ukrainian format
- [ ] translate "Основна довірена особа.Тип довіреної особи"
