### ISSUE TITLE
Fix datepicker bugs

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.web#708]
- [x] in case I put data, then delete it the error with filters occurs
![image](https://user-images.githubusercontent.com/31403196/51571404-edf83c00-1e56-11e9-8b1f-712142e36ed4.png)
- [x] if i manually input data and do not choose it from calendar date in calendar and date in input field doesn't match each other
![image](https://user-images.githubusercontent.com/31403196/51571506-2861d900-1e57-11e9-8689-5ec8c4100f59.png)

**Comment by ephor** [comment]
Dana check this out)

**Comment by danakonovalenko** [comment]
now calendar shows a day earlier than input date
![image.png](https://zube.io/files/edenlabllc/68090208e8f31fed38fb7e3b664697af-image.png)

**Comment by ephor** [comment]
It`s because of you in a different timezone
