### ISSUE TITLE
get medical program list/details FE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#742]
- [ ] feature
- [ ] design

**Comment by ephor** [comment]
Обсудить с Дианой детали реализации

**Comment by svetavedmed** [comment]
![Screen Shot 2019-02-28 at 7.51.21 PM.png](https://zube.io/files/edenlabllc/e89f766c031fe4c88de43a05e31ba3b4-screen-shot-2019-02-28-at-7-51-21-pm.png)

**Comment by svetavedmed** [comment]
inserted_at is wrong for medical programs
