### ISSUE TITLE
get brand(medication) list FE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#785]

**Comment by ephor** [comment]
Blocked by edenlabllc/ehealth.api#4187

**Comment by svetavedmed** [comment]
- [ ] use dictionary for `Країна виробника SL`, please

**Comment by svetavedmed** [comment]
- [ ] close msg "are you sure?" in case it was forbidden to deactivate medication
https://admin.dev.asclepius.com.ua/medications/TWVkaWNhdGlvbjpkNjdhNDM2Mi04NWQ5LTQxZjItOTBjOC0zYTc0YzUyNTg0NTc=/ingredients

**Comment by svetavedmed** [comment]
- [ ] wrong filter by innmDosage, should be by InnmDosage name

**Comment by svetavedmed** [comment]
- [ ] sometimes table with medications(brand) is not shown
