### ISSUE TITLE
Changes to registration screens

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.web#796]
As a user who registered in eHealth I want to see emails and screens with changes in this file
https://docs.google.com/document/d/1JymfUb7deSeOJSe34f0l4wpG8zeMsASGIrg7HuXLGH8/edit#heading=h.nwtfcdhl1gt4

**Comment by svetavedmed** [comment]
1. 
   - Тема листа: is wrong, should be `Вітаємо в системі eHealth!`
   - after `з роллю: : ` there are two colons
   - `Для підтвердження створення вашого облікового запису з відповідною роллю і функціями, будь ласка, перейдіть за посиланням:` should be not in bold
   - not `З повагою, ДП “Електронне здоров’я” та Національна служба здоров'я України`, but `З повагою, Національна служба здоров'я України та  ДП “Електронне здоров’я”`

**Comment by svetavedmed** [comment]
3. Зміни на екрані первинної реєстрації
   - the text is absent `Зверніть увагу, що приймаючи запрошення, Ви погоджуєтесь на обробку Ваших персональних даних з метою забезпечення роботи в Електронній системі охорони здоров’я`

**Comment by svetavedmed** [comment]
2. Текст шаблону листа після прийняття запрошення = підтвердження облікового запису користувача:
   - not З повагою, ДП “Електронне здоров’я” та Національна служба здоров'я України, but З повагою, Національна служба здоров'я України та ДП “Електронне здоров’я”

**Comment by svetavedmed** [comment]
3. Текст шаблону листа  для відновлення паролю
   - no image even if I ask to show image in this letter
   - `Тема листа:` is wrong
   - sign is wrong

 ```
Дякуємо за те, що ви з нами!
ДП “Електронне здоров’я” та Національна служба здоров'я України
Всі права захищено
``` should be
```
З повагою, 
Національна служба здоров'я України та  ДП “Електронне здоров’я”
Всі права захищено
```

**Comment by svetavedmed** [comment]
4. Зміни на екрані детальної інформації первинної реєстрації/реєстрації нової роллі
   - `Сховати деталі` is wrong, should be `Сховати деталі про персональні дані`
