### ISSUE TITLE
Change accreditation and licenses FE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.web#875]
#### Description

As le data model is changed it also should be change for graphQL and Admin Panel  

#### Context

Legal entity is change as new le types are added. So all these types with updated structure should be done for Admin panel. Temporary [create legal entity v1](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity) will also be used, so we should organize structure of legal entities for different le types and DB structures. 
In case LE was create with v1 method we return data as it is
In case LE is create with v2 method and has EDR data - we return new data structure. 
That is why schema has all these fields as optional.

#### What changes

Legal entity

#### Documentation, Adoption

1. [Confluence](https://edenlab.atlassian.net/wiki/spaces/EH/pages/740884491/Table+specs)
1. [Apiary or Schema](https://github.com/edenlabllc/ehealth.schema/pull/110)

**Comment by ephor** [comment]
Blocked by https://zube.io/edenlabllc/e-health/c/5965

**Comment by burlachenkovv** [comment]
Partially done, full implementation blocked by #4660
