### ISSUE TITLE
View/Update 2FA via Cabinet FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.web#9]
_From @danakonovalenko on March 16, 2018 11:42_

As an authorized user I want to be able to change second factor of authorization:
https://edenlab.atlassian.net/wiki/x/EYMoGg

In order to be able I need to have a pages (according to [design](https://marvelapp.com/7i06dia/screen/39670170):
- to view my current phone
- to set the new one
- to approve with OTP

_Copied from original issue: edenlabllc/ehealth.api#1956_

**Comment by svetavedmed** [comment]
in case authentication_factors is not presented, should not be shown link to log_in
