### ISSUE TITLE
Show tasks for legalEntityDeactivationJobs and legalEntityMergeJobs

### ISSUE THREAD

**Issue by PavelVesnin** [edenlabllc/ehealth.web#927]
As a NHS admin
I want to see all tasks for jobs with details.
So that should be implemented new page with tasks details (or expandable row with paging).

**Comment by burlachenkovv** [comment]
LegalEntityDeactivationJobs ready for test, but testing legalEntityMergeJobs is blocked by BE 500-response (the problem is localized and taken under control by BE team).
