### ISSUE TITLE
Add type to Medical Program creation

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.web#930]
#### Description
Based on the fact that we develop a new functionality of `program services` we need to make changes to the existing functionality of `medical program`

#### Context

As NHS Admin
I want to create a new medical program and choose its type
So that we need to add select input with field `type` and prefilled values from dictionaries. Dictionary key `MEDICAL_PROGRAM_TYPE`.

#### What changes

We have not previously passed the type of medical program, now it is a required field

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
Points has been updated because of adding Fragments and dividing MedicalPrograms into separate files under this task.

**Comment by novohatnya** [comment]
- [ ] add validation field `name` medical program by pattern `^[А-Яа-яЁёЇїІіЄєҐґ'\\- ]*$`
