### ISSUE TITLE
Services list page

### ISSUE THREAD

**Issue by ephor** [edenlabllc/ehealth.web#932]
#### Description
We have a new page with services on which we can see the list of services. We see such columns - 
[schema](https://github.com/edenlabllc/ehealth.schema/blob/4dbc01aa680cf51a246e34e2b8ce12c0db8e1de9/__schema__/services.graphql#L96-L118).
We can filtered by name, code, isActive and category.
We can sort table by name and inserted_at.

#### Context

As NHS Admin
I want to see list of services, filter and order table.

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
