### ISSUE TITLE
Service group list page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#934]
#### Description
A service group may be a subgroup of another service group. The service groups should be displayed as plane structure.
We need a new page with service group on which we can see the list of service groups. We see such columns - [schema](https://github.com/edenlabllc/ehealth.schema/blob/4dbc01aa680cf51a246e34e2b8ce12c0db8e1de9/__schema__/serviceGroup.graphql#L138-L189).
The last child must have link to list of services, filtered by `code`.

We can filtered by name, code, isActive .
We can sort table by name and inserted_at.

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
