### ISSUE TITLE
Program services list page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#937]
#### Description
We have a new page with program services on which we can see the list of services or service groups. We see such columns - [schema](https://github.com/edenlabllc/ehealth.schema/blob/4dbc01aa680cf51a246e34e2b8ce12c0db8e1de9/__schema__/programServices.graphql#L132-L156).
Default columns - database_id, name of medical program, name of service, name of service group, isActive, consumer_price, inserted_at. And hide other fields by default.
We don't show `description` and other information about service, service group.
We can filtered by name of medical program, name of service, name of service group, isActive and requestAllowed.
We can sort table by consumer_price and inserted_at.

#### Context

As NHS Admin
I want to see list of program services, filter and order table.
This page links services, service group with medical program ( `type` = service) (it's like program medication).

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
