### ISSUE TITLE
Program service `Create` mutation

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#938]
#### Description
In order to find the service_id, service_group_id, medical_program_id you need to search by name. (one of two fields must be filled - service_id or service_group_id)
Also we need fields - requestAllowed, consumerPrice and description
#### Context

As NHS Admin
I want to create program service.
So that I want to see button to create that opens popup and contains the fields according to the schema.
#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
