### ISSUE TITLE
Create mutations for Services group

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#939]
#### Description
In order to find the parent group id you need to search by name.
#### Context

As NHS Admin
I want to create service group.
So that I want to see button to create that opens popup and contains the fields according to the schema.

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
