### ISSUE TITLE
Deactivate and update mutations of Service group

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#940]
#### Context

As NHS Admin
I want deactivate service group and update field `requestAllowed`.
So that I want to see button to deactivate on the details page and button to update field `requestAllowed`. This buttons open popups. 
#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
