### ISSUE TITLE
Add service to service group  mutations for Services group

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#941]
#### Description
In order to find the service_id and service_group_id you need to search by name of service and name of service group.
#### Context

As NHS Admin
I want to create service group.
So that I want to see button to add service to service group that opens popup and contains the fields according to the schema.

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.

**Comment by novohatnya** [comment]
- [ ] Proposal to change the design of adding a server to a button

**Comment by novohatnya** [comment]
- [ ] if two service have same name, we don't know which service to choose. Add code?
