### ISSUE TITLE
Delete service from service group mutation on Service group page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#942]
#### Description
In order to find the service_id and serviceGroup_id you need to search by name of service or name of service group.
#### Context

As NHS Admin
I want to create service group.
So that I want to see button to delete service from service group that opens popup and contains the fields according to the schema.

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
