### ISSUE TITLE
Program service details page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#944]
#### Description
We have page with details of program services on which we can see information about program service, service, service group and medical program.

**HEADER**
- database program service
- isActive
- requestAllowed

**GENERAL INFO**
- description
- consumer_price

**MEDICAL PROGRAM**
- databaseId
- name
- isActive

**SERVICE**
- database_id
- name
- code
- category 
- isActive
- requestAllowed

**SERVICE GROUP**
- database_id
- name
- code 
- isActive
- requestAllowed

#### Context

As NHS Admin
I want to see information list of program services
This page describe services (or service group) and medical program ( `type` = service) (it's like program medication).

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
