### ISSUE TITLE
Service detail page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#948]
#### Description
We have page with details of services on which we can see information about service.

**HEADER**
- database id service
- isActive
- requestAllowed

**SERVICE GROUP**
Show the list of service groups which includes this service. Services have links.

#### Context

As NHS Admin
I want to see information about service.
This page describe services and has list of service groups which includes this service

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
