### ISSUE TITLE
Service group detail page

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.web#950]
#### Description
We have page with details of service groups on which we can see information about service group.

**HEADER**
- database id service group
- isActive
- requestAllowed
- name of parent service group. It must be a link.

**SERVICE**
Show the list of services which contains this service group. Service must have link.

#### Context

As NHS Admin
I want to see information about service.
This page describe services and has list of service groups which includes this service

#### Documentation, Adoption

1. [Schema](https://github.com/edenlabllc/ehealth.schema/pull/111/files)

**Comment by burlachenkovv** [comment]
For the moment, done with mock data.
